# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'evapo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(821, 615)
        MainWindow.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0))")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fileLocation = QtWidgets.QTextEdit(self.centralwidget)
        self.fileLocation.setGeometry(QtCore.QRect(10, 220, 581, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.fileLocation.setFont(font)
        self.fileLocation.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.fileLocation.setObjectName("fileLocation")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 300, 631, 51))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.pushButton.setObjectName("pushButton")
        self.statusFixed = QtWidgets.QLabel(self.centralwidget)
        self.statusFixed.setGeometry(QtCore.QRect(80, 400, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.statusFixed.setFont(font)
        self.statusFixed.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.statusFixed.setObjectName("statusFixed")
        self.statusPrinter = QtWidgets.QLabel(self.centralwidget)
        self.statusPrinter.setGeometry(QtCore.QRect(180, 400, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.statusPrinter.setFont(font)
        self.statusPrinter.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.statusPrinter.setText("")
        self.statusPrinter.setObjectName("statusPrinter")
        self.browseButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseButton.setGeometry(QtCore.QRect(600, 220, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(18)
        self.browseButton.setFont(font)
        self.browseButton.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.browseButton.setObjectName("browseButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Predict"))
        self.statusFixed.setText(_translate("MainWindow", "Status"))
        self.browseButton.setText(_translate("MainWindow", "Browse"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
